name: Build Android NDK Shared Library

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ndk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and unzip Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip

    - name: Build shared library
      run: |
        export ANDROID_NDK=$PWD/android-ndk-r25b
        $ANDROID_NDK/ndk-build

    - name: Upload built .so files
      uses: actions/upload-artifact@v4
      with:
        name: native-libs
        path: libs/
